language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check -Dpre-dex-libraries=false -Dabort-on-error=false

sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
